const $=s=>document.querySelector(s);const ADMIN_EMAILS=['judyqianqianovo@gmail.com'];const seed=[{image:'assets/gull-rock.jpg'},{image:'assets/hands.jpg'},{image:'assets/sunset.jpg'},{image:'assets/lamp.jpg'}];const rotations=['-3deg','2deg','-1deg','3deg'];
const works=()=>{try{return JSON.parse(localStorage.getItem('daybookWorks')||localStorage.getItem('lookbookWorks')||localStorage.getItem('lightworks')||'[]')}catch{return[]}};const save=x=>localStorage.setItem('daybookWorks',JSON.stringify(x));const toast=t=>{const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2600)};const safe=t=>{const e=document.createElement('div');e.textContent=t||'';return e.innerHTML};
const hiddenSeed=()=>{try{return JSON.parse(localStorage.getItem('daybookHiddenSeed')||'[]')}catch{return[]}};const saveHiddenSeed=ids=>localStorage.setItem('daybookHiddenSeed',JSON.stringify(ids));let activeFolder='all',galleryExpanded=false;
const seedDetails=[{category:'landscape',author:'Judy Zhu'},{category:'people',author:'Judy Zhu'},{category:'landscape',author:'Judy Zhu'},{category:'city',author:'Judy Zhu'}];
const extraPhotography=[{image:'assets/times-square.jpg',category:'city',author:'Judy Zhu',id:'seed-extra-0',seed:true},{image:'assets/bridge.jpg',category:'landscape',author:'Judy Zhu',id:'seed-extra-1',seed:true},{image:'assets/lucas-lake.jpg',category:'landscape',author:'Lucas Kouxu',id:'seed-lucas-0',seed:true},{image:'assets/lucas-train.jpg',category:'landscape',author:'Lucas Kouxu',id:'seed-lucas-1',seed:true},{image:'assets/lucas-mountains.jpg',category:'landscape',author:'Lucas Kouxu',id:'seed-lucas-2',seed:true}];
const featuredVideos=[{image:'assets/lucas-kouxu.mp4',category:'landscape',author:'Lucas Kouxu',mediaType:'video',id:'featured-video-0'}];
function renderGallery(){const editor=Boolean(sessionStorage.getItem('daybookEditor'));const hidden=hiddenSeed();const all=[...seed.map((work,index)=>({...work,...seedDetails[index],id:`seed-${index}`,seed:true})).filter(work=>!hidden.includes(work.id)),...works().filter(work=>work.status==='approved')];const shown=activeFolder==='all'?all:all.filter(work=>(work.category||'city')===activeFolder);$('#approvedGrid').innerHTML=shown.length?shown.map((work,index)=>`<article class="approved-piece" style="--rotate:${rotations[index%4]}"><img src="${work.image}" alt="Approved photography"><p class="approved-by">${safe(work.author||'Daybook contributor')}</p>${editor?`<button class="delete-gallery-photo" data-id="${work.id}" data-seed="${Boolean(work.seed)}" aria-label="Delete this photograph">×</button>`:''}</article>`).join(''):'<p class="gallery-empty">No photographs in this folder yet.</p>'}
function renderReviews(){const pending=works().filter(w=>w.status==='pending');$('#reviewList').innerHTML=pending.length?pending.map(w=>`<article class="review-item"><img src="${w.image||'assets/grass.jpg'}" alt=""><div><h3>${safe(w.author)}</h3><p>${safe(w.description)}</p></div><div class="review-actions"><button class="approve" data-id="${w.id}" data-action="approve">PUBLISH</button><button data-id="${w.id}" data-action="reject">PASS</button></div></article>`).join(''):'<p class="hand">Nothing waiting for an edit.</p>'}
$('#photo').onchange=e=>{const f=e.target.files[0];if(!f)return;if(f.size>10*1024*1024){toast('Choose an image under 10 MB.');e.target.value='';return}const r=new FileReader;r.onload=()=>{$('#preview').src=r.result;$('#preview').style.display='block'};r.readAsDataURL(f)};
$('#submissionForm').onsubmit=e=>{e.preventDefault();const d=new FormData(e.currentTarget),image=$('#preview').src.startsWith('data:')?$('#preview').src:'';if(!image){toast('Choose a photograph first.');return}try{save([...works(),{id:String(Date.now()),author:d.get('author'),description:d.get('description'),image,status:'pending'}]);e.currentTarget.reset();$('#preview').removeAttribute('src');$('#preview').style.display='none';toast('Your frame is with the editors.')}catch{toast('That image is too large for this demo.')}};
$('#adminOpen').onclick=()=>sessionStorage.getItem('daybookEditor')?($('#reviewDialog').showModal(),renderReviews()):$('#loginDialog').showModal();$('#loginForm').onsubmit=e=>{e.preventDefault();const email=$('#editorEmail').value.trim().toLowerCase();if(!ADMIN_EMAILS.includes(email)){toast('This email does not have editorial access.');return}sessionStorage.setItem('daybookEditor',email);$('#loginDialog').close();$('#reviewDialog').showModal();renderReviews()};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).close());$('#reviewList').onclick=e=>{const action=e.target.dataset.action,id=e.target.dataset.id;if(!action)return;save(works().map(w=>w.id===id?{...w,status:action==='approve'?'approved':'rejected'}:w));renderReviews();renderGallery();toast(action==='approve'?'Published to the gallery.':'Passed on.')};$('#playReel')?.addEventListener('click',()=>toast('Video reel coming soon.'));renderGallery();
document.querySelector('.hero-polaroid figcaption').textContent='New York City, Brooklyn Bridge';
document.querySelector('.hero h1').innerHTML='A way to<br><em>see the world.</em>';

const closeWithMotion=dialog=>{if(!dialog?.open)return;dialog.classList.add('dialog-closing');setTimeout(()=>{dialog.close();dialog.classList.remove('dialog-closing')},160)};
document.querySelectorAll('[data-close]').forEach(button=>button.onclick=()=>closeWithMotion($('#'+button.dataset.close)));

$('#photo').onchange=event=>{const file=event.target.files[0];if(!file)return;if(file.size>10*1024*1024){toast('Choose an image under 10 MB.');event.target.value='';return}const reader=new FileReader;reader.onload=()=>{const preview=$('#preview');preview.classList.remove('preview-in');preview.src=reader.result;preview.style.display='block';requestAnimationFrame(()=>preview.classList.add('preview-in'))};reader.readAsDataURL(file)};

$('#submissionForm').onsubmit=event=>{event.preventDefault();const data=new FormData(event.currentTarget),preview=$('#preview'),image=preview.src.startsWith('data:')?preview.src:'';if(!image){toast('Choose a photograph first.');return}try{save([...works(),{id:String(Date.now()),author:data.get('author'),category:data.get('category'),description:data.get('description'),image,status:'pending'}]);event.currentTarget.reset();preview.removeAttribute('src');preview.style.display='none';preview.classList.remove('preview-in');toast('Your frame is with the editors.')}catch{toast('That image is too large for this demo.')}};

$('#loginForm').onsubmit=event=>{event.preventDefault();const email=$('#editorEmail').value.trim().toLowerCase();if(!ADMIN_EMAILS.includes(email)){toast('This email does not have editorial access.');return}sessionStorage.setItem('daybookEditor',email);renderGallery();closeWithMotion($('#loginDialog'));setTimeout(()=>{$('#reviewDialog').showModal();renderReviews()},160)};

$('#reviewList').onclick=event=>{const action=event.target.dataset.action,id=event.target.dataset.id;if(!action)return;save(works().map(work=>work.id===id?{...work,status:action==='approve'?'approved':'rejected'}:work));renderReviews();renderGallery();if(action==='approve')requestAnimationFrame(()=>document.querySelector('#approvedGrid .approved-piece:last-child')?.classList.add('is-new'));toast(action==='approve'?'Published to the gallery.':'Passed on.')};
$('#approvedGrid').onclick=event=>{const button=event.target.closest('.delete-gallery-photo');if(!button||!sessionStorage.getItem('daybookEditor'))return;if(!confirm('Remove this photograph from the gallery?'))return;const id=button.dataset.id;if(button.dataset.seed==='true')saveHiddenSeed([...new Set([...hiddenSeed(),id])]);else save(works().filter(work=>work.id!==id));renderGallery();toast('Removed from the gallery.')};
document.querySelector('.folder-tabs').onclick=event=>{const button=event.target.closest('.folder-tab');if(!button)return;activeFolder=button.dataset.folder;document.querySelectorAll('.folder-tab').forEach(tab=>tab.classList.toggle('active',tab===button));renderGallery()};

const dailyDefaults=['assets/bench.jpg','assets/gull-pier.jpg','assets/stickers.jpg','assets/grass.jpg'];
const dailyPicks=()=>{try{return JSON.parse(localStorage.getItem('daybookDailyPicks')||'null')||dailyDefaults}catch{return dailyDefaults}};
const dailyChoices=()=>[...seed.map((work,index)=>({image:work.image,label:`by ${seedDetails[index].author}`,uploadedAt:Date.UTC(2026,8,1)})),...extraPhotography.map(work=>({image:work.image,label:`by ${work.author}`,uploadedAt:Date.UTC(2026,8,1)})),...works().filter(work=>work.status==='approved'&&work.mediaType!=='video').map(work=>({image:work.image,label:`by ${work.author||'Daybook contributor'}`,uploadedAt:work.createdAt||Date.now()}))];
function renderDailyPicks(){dailyPicks().slice(0,4).forEach((image,index)=>{const frame=$(`#dailyPick${index}`),choice=dailyChoices().find(item=>item.image===image),credit=document.querySelectorAll('.four-up figure b')[index];if(frame)frame.src=image;if(credit)credit.textContent=choice?.label||'by Judy Zhu'})}
const imageViewer=$('#imageViewer'),imageViewerPhoto=$('#imageViewerPhoto');document.querySelectorAll('.four-up img').forEach(image=>image.addEventListener('dblclick',()=>{imageViewerPhoto.src=image.currentSrc||image.src;imageViewerPhoto.alt=image.alt;imageViewer.showModal()}));imageViewer?.addEventListener('click',event=>{if(event.target===imageViewer)imageViewer.close()});
function ensureDailyEditor(){let editor=$('.daily-editor');if(editor)return editor;editor=document.createElement('section');editor.className='daily-editor';editor.innerHTML='<p class="kicker">EDIT MONTHLY PICKS</p><div id="dailyPickControls"></div><button id="saveDailyPicks" class="submit-button" type="button">SAVE MONTHLY PICKS</button>';$('#reviewList').after(editor);return editor}
function renderDailyEditor(){const editor=ensureDailyEditor(),choices=dailyChoices(),current=dailyPicks();editor.querySelector('#dailyPickControls').innerHTML=Array.from({length:4},(_,slot)=>`<label>FRAME ${String(slot+1).padStart(2,'0')}<select data-daily-slot="${slot}">${choices.map((choice,index)=>`<option value="${index}" ${choice.image===current[slot]?'selected':''}>${safe(choice.label)}</option>`).join('')}</select></label>`).join('');editor.querySelector('#saveDailyPicks').onclick=()=>{const selected=[...editor.querySelectorAll('select')].map(select=>choices[Number(select.value)].image);localStorage.setItem('daybookDailyPicks',JSON.stringify(selected));renderDailyPicks();toast('Daily picks updated.')}}
$('#adminOpen').onclick=()=>{if(sessionStorage.getItem('daybookEditor')){$('#reviewDialog').showModal();renderReviews();renderDailyEditor()}else $('#loginDialog').showModal()};
$('#loginForm').onsubmit=event=>{event.preventDefault();const email=$('#editorEmail').value.trim().toLowerCase();if(!ADMIN_EMAILS.includes(email)){toast('This email does not have editorial access.');return}sessionStorage.setItem('daybookEditor',email);renderGallery();closeWithMotion($('#loginDialog'));setTimeout(()=>{$('#reviewDialog').showModal();renderReviews();renderDailyEditor()},160)};
renderDailyPicks();
function renderDailyEditor(){const editor=ensureDailyEditor(),library=dailyChoices(),monthStart=Date.now()-30*24*60*60*1000,choices=library.filter(choice=>choice.uploadedAt>=monthStart),current=dailyPicks();editor.querySelector('#dailyPickControls').innerHTML=`<div class="monthly-library"><p>ALL PHOTOGRAPHY</p><div>${library.map(choice=>`<figure><img src="${choice.image}" alt="${safe(choice.label)}"><figcaption>${safe(choice.label)}</figcaption></figure>`).join('')}</div></div>`+Array.from({length:4},(_,slot)=>{const selectedIndex=Math.max(0,choices.findIndex(choice=>choice.image===current[slot]));return `<label class="daily-picker"><img src="${choices[selectedIndex].image}" alt="Selected monthly photograph"><span>FRAME ${String(slot+1).padStart(2,'0')}</span><select data-daily-slot="${slot}">${choices.map((choice,index)=>`<option value="${index}" ${index===selectedIndex?'selected':''}>${safe(choice.label)}</option>`).join('')}</select></label>`}).join('');editor.querySelectorAll('[data-daily-slot]').forEach(select=>select.onchange=()=>{select.closest('.daily-picker').querySelector('img').src=choices[Number(select.value)].image});editor.querySelector('#saveDailyPicks').onclick=()=>{const selected=[...editor.querySelectorAll('select')].map(select=>choices[Number(select.value)].image);localStorage.setItem('daybookDailyPicks',JSON.stringify(selected));renderDailyPicks();toast('Monthly picks updated.')}}
function renderReviews(){const pending=works().filter(work=>work.status==='pending');$('#reviewList').innerHTML=pending.length?pending.map(work=>`<article class="review-item">${work.mediaType==='video'?`<video src="${work.image}" muted playsinline></video>`:`<img src="${work.image||'assets/grass.jpg'}" alt="">`}<div><h3>${safe(work.author)}</h3><p>${safe(work.description)}</p></div><div class="review-actions"><button class="approve" data-id="${work.id}" data-action="approve">PUBLISH</button><button data-id="${work.id}" data-action="reject">PASS</button></div></article>`).join(''):'<p class="hand">Nothing waiting for an edit.</p>'}
function renderVideoGallery(){const gallery=$('#videoGallery');if(!gallery)return;gallery.querySelectorAll('[data-uploaded-video]').forEach(tile=>tile.remove());works().filter(work=>work.status==='approved'&&work.mediaType==='video').forEach((work,index)=>gallery.insertAdjacentHTML('beforeend',`<article class="video-tile uploaded-video" data-uploaded-video style="--video-rotate:${index%2?'2deg':'-2deg'}"><video src="${work.image}" controls playsinline preload="metadata"></video><span>by ${safe(work.author||'Daybook contributor')}</span></article>`))}
$('#mediaType').onchange=event=>{const video=event.target.value==='video';$('#mediaLabel').firstChild.textContent=video?'VIDEO':'PHOTO';$('#photo').accept=video?'video/*':'image/*';$('#photo').value='';$('#preview').style.display='none';$('#preview').removeAttribute('src');$('#videoPreview').style.display='none';$('#videoPreview').removeAttribute('src')};
$('#photo').onchange=event=>{const file=event.target.files[0],video=$('#mediaType').value==='video';if(!file)return;if(file.size>(video?4:10)*1024*1024){toast(video?'Choose a video under 4 MB.':'Choose an image under 10 MB.');event.target.value='';return}const reader=new FileReader;reader.onload=()=>{if(video){const preview=$('#videoPreview');preview.src=reader.result;preview.style.display='block'}else{const preview=$('#preview');preview.classList.remove('preview-in');preview.src=reader.result;preview.style.display='block';requestAnimationFrame(()=>preview.classList.add('preview-in'))}};reader.readAsDataURL(file)};
$('#submissionForm').onsubmit=event=>{event.preventDefault();const data=new FormData(event.currentTarget),mediaType=data.get('mediaType'),preview=mediaType==='video'?$('#videoPreview'):$('#preview'),source=preview.src.startsWith('data:')?preview.src:'';if(!source){toast(`Choose a ${mediaType==='video'?'video':'photograph'} first.`);return}try{save([...works(),{id:String(Date.now()),createdAt:Date.now(),author:data.get('author'),category:data.get('category'),description:data.get('description'),image:source,mediaType,status:'pending'}]);event.currentTarget.reset();$('#preview').removeAttribute('src');$('#preview').style.display='none';$('#videoPreview').removeAttribute('src');$('#videoPreview').style.display='none';toast('Your work is with the editors.')}catch{toast('That file is too large for this demo.')}};
$('#reviewList').onclick=event=>{const action=event.target.dataset.action,id=event.target.dataset.id;if(!action)return;const work=works().find(item=>item.id===id);save(works().map(item=>item.id===id?{...item,status:action==='approve'?'approved':'rejected'}:item));renderReviews();renderGallery();renderVideoGallery();if(action==='approve'&&work?.mediaType!=='video')requestAnimationFrame(()=>document.querySelector('#approvedGrid .approved-piece:last-child')?.classList.add('is-new'));toast(action==='approve'?'Published to the gallery.':'Passed on.')};
renderVideoGallery();
let activeVideoFolder='all';
const galleryVideoSeed=[{image:'assets/times-square.jpg',category:'city',label:'CITY AFTER RAIN'},{image:'assets/bridge.jpg',category:'landscape',label:'ON THE WAY'},{image:'assets/hands.jpg',category:'people',label:'HANDHELD'}];
function renderGallery(){const editor=Boolean(sessionStorage.getItem('daybookEditor'));const hidden=hiddenSeed();const all=[...seed.map((work,index)=>({...work,...seedDetails[index],id:`seed-${index}`,seed:true})).filter(work=>!hidden.includes(work.id)),...works().filter(work=>work.status==='approved'&&work.mediaType!=='video')];const shown=activeFolder==='all'?all:all.filter(work=>(work.category||'city')===activeFolder);$('#approvedGrid').innerHTML=shown.length?shown.map((work,index)=>`<article class="approved-piece" style="--rotate:${rotations[index%4]}"><img src="${work.image}" alt="Approved photography"><p class="approved-by">${safe(work.author||'Daybook contributor')}</p>${editor?`<button class="delete-gallery-photo" data-id="${work.id}" data-seed="${Boolean(work.seed)}" aria-label="Delete this photograph">×</button>`:''}</article>`).join(''):'<p class="gallery-empty">No photographs in this folder yet.</p>'}
function renderGalleryVideos(){const all=[...galleryVideoSeed,...works().filter(work=>work.status==='approved'&&work.mediaType==='video')];const shown=activeVideoFolder==='all'?all:all.filter(work=>(work.category||'city')===activeVideoFolder);$('#galleryVideoGrid').innerHTML=shown.length?shown.map(work=>`<article class="gallery-video-card">${work.mediaType==='video'?`<video src="${work.image}" controls playsinline preload="metadata"></video>`:`<img src="${work.image}" alt="${safe(work.label)}">`}<p>${work.mediaType==='video'?`by ${safe(work.author||'Daybook contributor')}`:safe(work.label)}</p></article>`).join(''):'<p class="gallery-empty">No videos in this folder yet.</p>'}
document.querySelector('.media-tabs').onclick=event=>{const button=event.target.closest('.media-tab');if(!button)return;const video=button.dataset.medium==='video';document.querySelectorAll('.media-tab').forEach(tab=>tab.classList.toggle('active',tab===button));$('#photoFolderArea').hidden=video;$('#videoFolderArea').hidden=!video;if(video)renderGalleryVideos()};
document.querySelector('#videoFolderArea .folder-tabs').onclick=event=>{const button=event.target.closest('.video-folder-tab');if(!button)return;activeVideoFolder=button.dataset.videoFolder;document.querySelectorAll('.video-folder-tab').forEach(tab=>tab.classList.toggle('active',tab===button));renderGalleryVideos()};
renderGallery();renderGalleryVideos();
$('#videographyNav')?.addEventListener('click',()=>setTimeout(()=>document.querySelector('.media-tab[data-medium="video"]')?.click(),0));
const galleryToggleButton=document.createElement('button');galleryToggleButton.id='galleryToggle';galleryToggleButton.className='gallery-toggle';galleryToggleButton.type='button';$('#approvedGrid').after(galleryToggleButton);function saveRenderedGalleryLayout(){if(!sessionStorage.getItem('daybookEditor'))return;const positions=galleryPositions();document.querySelectorAll('#approvedGrid [data-gallery-id]').forEach(piece=>{positions[piece.dataset.galleryId]={x:Number(piece.dataset.dragX)||0,y:Number(piece.dataset.dragY)||0}});saveGalleryPositions(positions)}galleryToggleButton.onclick=()=>{saveRenderedGalleryLayout();galleryExpanded=!galleryExpanded;renderGallery()};
let draggedPiece=null,dragStartX=0,dragStartY=0;$('#approvedGrid').addEventListener('pointerdown',event=>{const piece=event.target.closest('.approved-piece');if(!piece||event.target.closest('.delete-gallery-photo'))return;draggedPiece=piece;dragStartX=event.clientX-(Number(piece.dataset.dragX)||0);dragStartY=event.clientY-(Number(piece.dataset.dragY)||0);piece.setPointerCapture(event.pointerId);piece.classList.add('is-dragging')});$('#approvedGrid').addEventListener('pointermove',event=>{if(!draggedPiece)return;const x=event.clientX-dragStartX,y=event.clientY-dragStartY;draggedPiece.dataset.dragX=x;draggedPiece.dataset.dragY=y;draggedPiece.style.setProperty('--drag-x',`${x}px`);draggedPiece.style.setProperty('--drag-y',`${y}px`)});$('#approvedGrid').addEventListener('pointerup',()=>{if(!draggedPiece)return;const piece=draggedPiece;piece.classList.remove('is-dragging');if(sessionStorage.getItem('daybookEditor')&&piece.dataset.galleryId){const positions=galleryPositions();positions[piece.dataset.galleryId]={x:Number(piece.dataset.dragX)||0,y:Number(piece.dataset.dragY)||0};saveGalleryPositions(positions)}draggedPiece=null});
renderGallery();
function renderVideoGallery(){const gallery=$('#videoGallery');if(!gallery)return;gallery.querySelectorAll('[data-uploaded-video]').forEach(tile=>tile.remove());[...featuredVideos,...works().filter(work=>work.status==='approved'&&work.mediaType==='video')].forEach((work,index)=>gallery.insertAdjacentHTML('beforeend',`<article class="video-tile uploaded-video" data-uploaded-video style="--video-rotate:${index%2?'2deg':'-2deg'}"><video src="${work.image}" controls playsinline preload="metadata"></video><span>by ${safe(work.author||'Daybook contributor')}</span></article>`))}
renderVideoGallery();
function galleryPositions(){try{return JSON.parse(localStorage.getItem('photoBookGalleryPositions')||'{}')}catch{return{}}}function saveGalleryPositions(positions){localStorage.setItem('photoBookGalleryPositions',JSON.stringify(positions))}function renderGallery(){const editor=Boolean(sessionStorage.getItem('daybookEditor'));const hidden=hiddenSeed(),positions=galleryPositions();const all=[...seed.map((work,index)=>({...work,...seedDetails[index],id:`seed-${index}`,seed:true})),...extraPhotography].filter(work=>!hidden.includes(work.id)).concat(works().filter(work=>work.status==='approved'&&work.mediaType!=='video'));const shown=activeFolder==='all'?all:all.filter(work=>(work.category||'city')===activeFolder),visible=galleryExpanded?shown:shown.slice(0,4);$('#approvedGrid').innerHTML=visible.length?visible.map((work,index)=>{const position=positions[work.id]||{};return `<article class="approved-piece" data-gallery-id="${work.id}" style="--rotate:${rotations[index%4]};--drag-x:${Number(position.x)||0}px;--drag-y:${Number(position.y)||0}px"><img src="${work.image}" alt="Approved photography"><p class="approved-by">${safe(work.author||'Judy Zhu')}</p>${editor?`<button class="delete-gallery-photo" data-id="${work.id}" data-seed="${Boolean(work.seed)}" aria-label="Delete this photograph">×</button>`:''}</article>`}).join(''):'<p class="gallery-empty">No photographs in this folder yet.</p>';const toggle=$('#galleryToggle');if(toggle){toggle.hidden=shown.length<=4;toggle.textContent=galleryExpanded?'COLLAPSE ↑':`SHOW MORE (${shown.length-4}) ↓`}}
function renderGalleryVideos(){const shown=[...featuredVideos,...works().filter(work=>work.status==='approved'&&work.mediaType==='video')].filter(work=>activeVideoFolder==='all'||(work.category||'city')===activeVideoFolder);$('#galleryVideoGrid').innerHTML=shown.length?shown.map(work=>`<article class="gallery-video-card"><video src="${work.image}" controls playsinline preload="metadata"></video><p>by ${safe(work.author||'Daybook contributor')}</p></article>`).join(''):'<p class="gallery-empty">No videos in this folder yet.</p>'}
renderGallery();renderGalleryVideos();
