const $=s=>document.querySelector(s),EDITOR_EMAIL='judyqianqianovo@gmail.com';
const db=window.supabase?.createClient(window.SUPABASE_URL,window.SUPABASE_PUBLISHABLE_KEY);
const rotations=['-3deg','2deg','-1deg','3deg'];
const staticPhotos=[
 {id:'seed-0',image:'assets/gull-rock.jpg',category:'landscape',author:'Judy Zhu'},
 {id:'seed-1',image:'assets/hands.jpg',category:'people',author:'Judy Zhu'},
 {id:'seed-2',image:'assets/sunset.jpg',category:'landscape',author:'Judy Zhu'},
 {id:'seed-3',image:'assets/lamp.jpg',category:'city',author:'Judy Zhu'},
 {id:'seed-extra-0',image:'assets/times-square.jpg',category:'city',author:'Judy Zhu'},
 {id:'seed-extra-1',image:'assets/bridge.jpg',category:'landscape',author:'Judy Zhu'},
 {id:'seed-lucas-0',image:'assets/lucas-lake.jpg',category:'landscape',author:'Lucas Kouxu'},
 {id:'seed-lucas-1',image:'assets/lucas-train.jpg',category:'landscape',author:'Lucas Kouxu'},
 {id:'seed-lucas-2',image:'assets/lucas-mountains.jpg',category:'landscape',author:'Lucas Kouxu'}];
const featuredVideos=[{id:'featured-video-0',url:'assets/lucas-kouxu.mp4',category:'landscape',author:'Lucas Kouxu',media_type:'video'}];
let remoteWorks=[],activeFolder='all',activeVideoFolder='all',galleryExpanded=false;
const safe=value=>{const el=document.createElement('div');el.textContent=value||'';return el.innerHTML};
const toast=message=>{const el=$('#toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),3000)};
const positionMap=()=>{try{return JSON.parse(localStorage.getItem('photoBookGalleryPositions')||'{}')}catch{return{}}};
const savePositions=value=>localStorage.setItem('photoBookGalleryPositions',JSON.stringify(value));
const dailyDefaults=['assets/bench.jpg','assets/gull-pier.jpg','assets/stickers.jpg','assets/grass.jpg'];
const dailyPicks=()=>{try{return JSON.parse(localStorage.getItem('photoBookDailyPicks')||'null')||dailyDefaults}catch{return dailyDefaults}};

async function isEditor(){if(!db)return false;const{data}=await db.auth.getUser();return data.user?.email?.toLowerCase()===EDITOR_EMAIL}
function mediaUrl(work){return work.url||db.storage.from('submissions').getPublicUrl(work.object_path).data.publicUrl}
async function refreshPublicWorks(){if(!db)return toast('Supabase configuration is missing.');const{data,error}=await db.from('submissions').select('*').eq('status','approved').order('created_at',{ascending:false});if(error){console.error(error);return toast('Could not load the online gallery.')}remoteWorks=(data||[]).map(work=>({...work,url:mediaUrl(work)}));renderGallery();renderGalleryVideos();renderDailyPicks()}
function allPhotos(){return[...staticPhotos,...remoteWorks.filter(work=>work.media_type==='image')]}
function renderGallery(){const all=allPhotos(),filtered=activeFolder==='all'?all:all.filter(work=>work.category===activeFolder),visible=galleryExpanded?filtered:filtered.slice(0,4),saved=positionMap();$('#approvedGrid').innerHTML=visible.length?visible.map((work,index)=>{const point=saved[work.id]||{},remove=work.object_path?`<button class="delete-gallery-photo" data-delete-id="${work.id}" aria-label="Delete this photograph">×</button>`:'';return`<article class="approved-piece" data-gallery-id="${work.id}" style="--rotate:${rotations[index%4]};--drag-x:${Number(point.x)||0}px;--drag-y:${Number(point.y)||0}px"><img src="${work.url||work.image}" alt="Photograph by ${safe(work.author)}"><p class="approved-by">${safe(work.author)}</p>${remove}</article>`}).join(''):'<p class="gallery-empty">No photographs in this folder yet.</p>';const toggle=$('#galleryToggle');toggle.hidden=filtered.length<=4;toggle.textContent=galleryExpanded?'COLLAPSE ↑':`SHOW MORE (${filtered.length-4}) ↓`}
function renderGalleryVideos(){const all=[...featuredVideos,...remoteWorks.filter(work=>work.media_type==='video')],shown=activeVideoFolder==='all'?all:all.filter(work=>work.category===activeVideoFolder);$('#galleryVideoGrid').innerHTML=shown.length?shown.map(work=>`<article class="gallery-video-card"><video src="${mediaUrl(work)}" controls playsinline preload="metadata"></video><p>by ${safe(work.author)}</p></article>`).join(''):'<p class="gallery-empty">No videos in this folder yet.</p>'}
function renderDailyPicks(){const choices=allPhotos().map(work=>({image:work.url||work.image,label:`by ${work.author}`}));dailyPicks().slice(0,4).forEach((image,index)=>{const choice=choices.find(item=>item.image===image),frame=$(`#dailyPick${index}`),credit=document.querySelectorAll('.four-up figure b')[index];if(frame)frame.src=image;if(credit)credit.textContent=choice?.label||'by Judy Zhu'})}

async function renderReviews(){if(!await isEditor())return;const{data,error}=await db.from('submissions').select('*').eq('status','pending').order('created_at',{ascending:false});if(error){console.error(error);return $('#reviewList').innerHTML='<p class="hand">Could not load submissions.</p>'}$('#reviewList').innerHTML=data?.length?data.map(work=>{const url=mediaUrl(work),preview=work.media_type==='video'?`<video src="${url}" muted controls playsinline></video>`:`<img src="${url}" alt="Submitted work">`;return`<article class="review-item">${preview}<div><h3>${safe(work.author)}</h3><p>${safe(work.email)} · ${safe(work.category)}</p><p>${safe(work.note)}</p></div><div class="review-actions"><button class="approve" data-action="approve" data-id="${work.id}">PUBLISH</button><button data-action="reject" data-id="${work.id}">PASS</button></div></article>`}).join(''):'<p class="hand">Nothing waiting for an edit.</p>'}
async function uploadMedia(file,path,button){if(file.size<=6*1024*1024){const{error}=await db.storage.from('submissions').upload(path,file,{contentType:file.type,upsert:false});if(error)throw error;return}if(!window.tus)throw new Error('Large-file uploader did not load.');const{data:{session}}=await db.auth.getSession(),projectId=new URL(window.SUPABASE_URL).hostname.split('.')[0],token=session?.access_token||window.SUPABASE_PUBLISHABLE_KEY;return new Promise((resolve,reject)=>{const upload=new tus.Upload(file,{endpoint:`https://${projectId}.storage.supabase.co/storage/v1/upload/resumable`,retryDelays:[0,3000,5000,10000,20000],headers:{authorization:`Bearer ${token}`,apikey:window.SUPABASE_PUBLISHABLE_KEY},uploadDataDuringCreation:true,removeFingerprintOnSuccess:true,metadata:{bucketName:'submissions',objectName:path,contentType:file.type,cacheControl:'3600'},chunkSize:6*1024*1024,onError:reject,onProgress:(loaded,total)=>button.textContent=`UPLOADING ${Math.round(loaded/total*100)}%`,onSuccess:resolve});upload.findPreviousUploads().then(previous=>{if(previous.length)upload.resumeFromPreviousUpload(previous[0]);upload.start()}).catch(reject)})}
async function submitWork(event){event.preventDefault();if(!db)return toast('Supabase configuration is missing.');const form=event.currentTarget,values=new FormData(form),file=$('#photo').files[0],mediaType=values.get('mediaType'),maxBytes=20*1024*1024;if(!file)return toast(`Choose a ${mediaType==='video'?'video':'photograph'} first.`);if(file.size>maxBytes)return toast('Choose a file under 20 MB.');const ext=(file.name.split('.').pop()||'jpg').replace(/[^a-z0-9]/gi,'').toLowerCase(),path=`${crypto.randomUUID()}.${ext}`,button=form.querySelector('[type="submit"]');button.disabled=true;button.textContent='UPLOADING…';try{await uploadMedia(file,path,button)}catch(uploadError){console.error(uploadError);button.disabled=false;button.textContent='SEND TO EDITORS ↗';return toast('Upload failed. Please try again.')}const{error:insertError}=await db.from('submissions').insert({author:values.get('author'),email:values.get('email'),category:values.get('category'),media_type:mediaType,object_path:path,note:values.get('description'),status:'pending'});button.disabled=false;button.textContent='SEND TO EDITORS ↗';if(insertError){console.error(insertError);return toast('Your file uploaded, but the submission record failed.')}form.reset();$('#preview').removeAttribute('src');$('#preview').style.display='none';$('#videoPreview').removeAttribute('src');$('#videoPreview').style.display='none';toast('Your work is with the editors.')}
async function sendEditorLink(event){event.preventDefault();const email=$('#editorEmail').value.trim().toLowerCase();if(email!==EDITOR_EMAIL)return toast('This email does not have editorial access.');const{error}=await db.auth.signInWithOtp({email,options:{emailRedirectTo:`${location.origin}${location.pathname}`}});if(error){console.error(error);return toast('Could not send the sign-in link.')}$('#loginDialog').close();toast('Check your email for the secure sign-in link.')}
async function handleReview(event){const button=event.target.closest('[data-action]');if(!button||!await isEditor())return;const status=button.dataset.action==='approve'?'approved':'rejected',{error}=await db.from('submissions').update({status}).eq('id',button.dataset.id);if(error)return toast('Could not update this submission.');await renderReviews();await refreshPublicWorks();toast(status==='approved'?'Published to the gallery.':'Passed on.')}
async function deleteRemoteWork(button){if(!await isEditor()||!confirm('Remove this photograph from the gallery?'))return;const work=remoteWorks.find(item=>item.id===button.dataset.deleteId);if(!work)return;const{error}=await db.from('submissions').delete().eq('id',work.id);if(error)return toast('Could not remove this work.');await db.storage.from('submissions').remove([work.object_path]);await refreshPublicWorks();toast('Removed from the gallery.')}

function previewFile(){const file=$('#photo').files[0],video=$('#mediaType').value==='video';if(!file)return;const url=URL.createObjectURL(file);if(video){$('#videoPreview').src=url;$('#videoPreview').style.display='block';$('#preview').style.display='none'}else{$('#preview').src=url;$('#preview').style.display='block';$('#videoPreview').style.display='none'}}
function setMediaType(){const video=$('#mediaType').value==='video';$('#mediaLabel').firstChild.textContent=video?'VIDEO':'PHOTO';$('#photo').accept=video?'video/*':'image/*';$('#photo').value='';$('#preview').style.display='none';$('#videoPreview').style.display='none'}
function startDrag(event){const piece=event.target.closest('.approved-piece');if(!piece||event.target.closest('button'))return;const id=piece.dataset.galleryId,saved=positionMap()[id]||{},startX=event.clientX-(Number(saved.x)||0),startY=event.clientY-(Number(saved.y)||0);piece.setPointerCapture(event.pointerId);piece.classList.add('is-dragging');const move=moveEvent=>{const x=moveEvent.clientX-startX,y=moveEvent.clientY-startY;piece.style.setProperty('--drag-x',`${x}px`);piece.style.setProperty('--drag-y',`${y}px`);piece.dataset.dragX=x;piece.dataset.dragY=y};const stop=()=>{piece.classList.remove('is-dragging');const all=positionMap();all[id]={x:Number(piece.dataset.dragX)||0,y:Number(piece.dataset.dragY)||0};savePositions(all);piece.removeEventListener('pointermove',move)};piece.addEventListener('pointermove',move);piece.addEventListener('pointerup',stop,{once:true})}
function initialize(){let toggle=$('#galleryToggle');if(!toggle){toggle=document.createElement('button');toggle.id='galleryToggle';toggle.className='gallery-toggle';toggle.type='button';$('#approvedGrid').after(toggle)}document.querySelectorAll('[data-close]').forEach(button=>button.onclick=()=> $(`#${button.dataset.close}`).close());$('#submissionForm').onsubmit=submitWork;$('#loginForm').onsubmit=sendEditorLink;$('#reviewList').onclick=handleReview;$('#photo').onchange=previewFile;$('#mediaType').onchange=setMediaType;$('#adminOpen').onclick=async()=>{if(await isEditor()){$('#reviewDialog').showModal();renderReviews()}else $('#loginDialog').showModal()};$('#approvedGrid').onclick=event=>{const button=event.target.closest('[data-delete-id]');if(button)deleteRemoteWork(button)};$('#approvedGrid').addEventListener('pointerdown',startDrag);toggle.onclick=()=>{galleryExpanded=!galleryExpanded;renderGallery()};document.querySelector('#photoFolderArea .folder-tabs').onclick=event=>{const button=event.target.closest('.folder-tab');if(!button)return;activeFolder=button.dataset.folder;galleryExpanded=false;document.querySelectorAll('.folder-tab').forEach(tab=>tab.classList.toggle('active',tab===button));renderGallery()};document.querySelector('.media-tabs').onclick=event=>{const button=event.target.closest('.media-tab');if(!button)return;const video=button.dataset.medium==='video';document.querySelectorAll('.media-tab').forEach(tab=>tab.classList.toggle('active',tab===button));$('#photoFolderArea').hidden=video;$('#videoFolderArea').hidden=!video;if(video)renderGalleryVideos()};document.querySelector('#videoFolderArea .folder-tabs').onclick=event=>{const button=event.target.closest('.video-folder-tab');if(!button)return;activeVideoFolder=button.dataset.videoFolder;document.querySelectorAll('.video-folder-tab').forEach(tab=>tab.classList.toggle('active',tab===button));renderGalleryVideos()};$('#videographyNav').onclick=()=>setTimeout(()=>document.querySelector('.media-tab[data-medium="video"]').click(),0);document.querySelectorAll('.four-up img').forEach(image=>image.ondblclick=()=>{$('#imageViewerPhoto').src=image.currentSrc||image.src;$('#imageViewerPhoto').alt=image.alt;$('#imageViewer').showModal()});$('#imageViewer').onclick=event=>{if(event.target===$('#imageViewer'))$('#imageViewer').close()};renderGallery();renderGalleryVideos();renderDailyPicks();refreshPublicWorks();db?.auth.onAuthStateChange(()=>refreshPublicWorks())}
initialize();
